version: '2'
services:
    rethinkdb-container:
        #restart: always
        image: rethinkdb
        hostname: rethinkdb
        volumes:
            - "/isard/src/database:/data"
        ports:
            - "8080:8080"
            - "28015:28015"
        expose:
            - "28015"
        networks:
            main:
                aliases:
                - rethinkdb

    isard-hypervisor:
        #restart: always
        image: isard/hypervisor
        build:
            context: .
            dockerfile: dockers/hypervisor/Dockerfile
        links:
            - "rethinkdb-container"
        hostname: isard-hypervisor
        ports:
            - "80:80"
            - "65024:22"
            - "5900-5930:5900-5930"
            - "55900-55930:55900-55930"
        expose:
            - "22"
        privileged: true
        volumes:
            - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
            - "sshkeys:/root/.ssh"
            - "/isard:/isard"
            - "/isard/builder:/root/.cache/virt-builder"
            - "/etc/hostname:/hostname"
            - "viewerkeys:/etc/pki/libvirt-spice"
        networks:
            main:
                aliases:
                - isard-hypervisor
        command: /usr/sbin/init

    isard-webapp:
        #restart: always
        image: isard/webapp
        build:
            context: .
            dockerfile: dockers/webapp/Dockerfile
        links:
            - "rethinkdb-container"
        hostname: isard-webapp
        volumes:
            - "viewerkeys:/isard/install/viewer-certs"
            - "/isard/src/isard:/isard"
        ports:
            - "65023:22"
        expose:
            - "5000"
        environment:
            PYTHONUNBUFFERED: 0
        networks:
            main:
                aliases:
                - isard-webapp
        command: python3 /isard/run_webapp.py

    isard-engine:
        #restart: always
        image: isard/engine
        build:
            context: .
            dockerfile: dockers/engine/Dockerfile
        links:
            - "rethinkdb-container"
            - "isard-hypervisor"
        volumes:
            - "sshkeys:/root/.ssh"
            - "/isard/src/isard:/isard"
        hostname: isard-engine
        ports:
            - "5555:5555"
            - "65022:22"
        expose:
            - "5555"
        environment:
            PYTHONUNBUFFERED: 0
        networks:
            main:
                aliases:
                - isard-engine
        command: bash -c '/init.sh'

    nginx:
        #restart: always
        image: marvambass/nginx-ssl-secure
        ports:
            - "443:443"
        volumes:
            - "./dockers/nginx/:/etc/nginx/external"
        hostname: nginx
        links:
            - "isard-webapp:isard-webapp"
        logging:
            driver: "none"
        networks:
            main:
                aliases:
                - nginx

networks:
    main:
volumes:
    sshkeys:
    viewerkeys:
